version: "3"

networks:
  backend:

services:
  web:
    restart: always
    build: ./web
    ports:
      - "80:8000" # django
    depends_on:
      - postgres
    volumes:
      - ./web:/app
    networks:
      - backend
    env_file: .env
    command: ./bootup.sh

  postgres:
    restart: always
    image: postgres:10.1
    expose:
      - "5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    networks:
      - backend
