# Generated by Django 3.1.4 on 2021-01-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
