# Generated by Django 3.1.4 on 2021-01-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0002_auto_20210101_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
    ]
