FROM python:3.7
RUN pip install --upgrade pip
RUN pip install Django==3.1.4
RUN pip install django-extensions==3.1.0
RUN pip install psycopg2-binary==2.8.6
RUN pip install django-cors-headers==3.6.0
RUN pip install ipython

WORKDIR /app
